version: '3'
services:
  web:
    image: msdeploybot/silverstripe-web
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 8080:80

  database:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=development

volumes:
  db-data:
